'use strict';
const fs = require('node:fs');
const path = require('node:path');
const { root } = require('./templates');
function writeOutputs(outputs, { check = false, obsolete = [] } = {}) {
  const changed = [];
  for (const [relative, content] of outputs) {
    const target = path.resolve(root, relative);
    if (!target.startsWith(root + path.sep)) throw new Error('Unsafe output path: ' + relative);
    if (fs.existsSync(target) && fs.readFileSync(target, 'utf8') === content) continue;
    changed.push(relative);
    if (!check) { fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content); }
  }
  for (const relative of obsolete) {
    const target = path.resolve(root, relative);
    if (!/^noticias\/[a-z0-9-]+\.html$/.test(relative) || !target.startsWith(root + path.sep)) throw new Error('Unsafe obsolete path: ' + relative);
    if (!fs.existsSync(target)) continue;
    if (!fs.readFileSync(target, 'utf8').includes('Generated by scripts/build-news.js.')) throw new Error('Unrecognized generated file: ' + relative);
    changed.push(relative);
    if (!check) fs.unlinkSync(target);
  }
  if (check && changed.length) { console.error('Rebuild required: ' + changed.join(', ')); process.exitCode = 1; }
  else console.log(check ? 'Generated files are up to date.' : `${changed.length} files updated.`);
}
module.exports = { writeOutputs };
