/* Build static editorial pages and the small home feed from one source of truth.
   Run: node scripts/build-news.js [--check]. No packages or network required. */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const E = require('../assets/js/shared/news-model.js');
const root = path.resolve(__dirname, '..');
const source = JSON.parse(fs.readFileSync(path.join(root, 'content/news.json'), 'utf8'));
const site = require('../config/site').url;
const renderHead = require('../src/components/head');
const renderHeader = require('../src/components/header');
const renderFooter = require('../src/components/footer');
const all = E.published(source.items);
const esc = E.escape;
const outputs = new Map();
const ids = new Set(), slugs = new Set();
for (const item of source.items) {
  if (!E.slug(item.slug) || !E.slug(item.id) || ids.has(item.id) || slugs.has(item.slug)) throw new Error(`Invalid/duplicate identity: ${item.id}`);
  if (!E.date(item.publishedAt) || !item.title || !item.category || !Array.isArray(item.blocks)) throw new Error(`Incomplete article: ${item.id}`);
  ids.add(item.id); slugs.add(item.slug);
}
const archiveURL = page => page === 1 ? 'noticias.html' : `noticias/pagina-${page}.html`;
const internal = new Map(all.map(i => [i.sourceUrl, E.url(i)]));
function contentLink(href, prefix) {
  if (internal.has(href)) return prefix + internal.get(href);
  if (/^https:\/\/fag\.tangua\.rj\.gov\.br\/category\/noticias\//.test(href)) return prefix+'noticias.html';
  if (/^https?:\/\//.test(href)) return E.safeURL(href);
  return E.safeURL(href) ? prefix+href : '';
}
function page({title, description, route, prefix='', body, article=false, archive=false, noindex=false, extraHead='', image}) {
  const head = renderHead({title:title+' — FAG', description, route, prefix, article, noindex, image,
    styles:['assets/css/components/news.css','assets/css/pages/editorial.css','assets/css/components/header.css'],
    scripts:['assets/js/components/header.js',...(archive?['assets/js/shared/news-model.js','assets/js/data/news-archive.js']:[]),'assets/js/components/news-interactions.js'],extra:extraHead});
  return `<!DOCTYPE html>
<!-- Generated by scripts/build-news.js. Edit content/news.json or src/components. -->
<html lang="pt-BR"><head>${head}</head>
<body class="editorial-page${article?' editorial-page--article':''}"><a class="skip-link" href="#conteudo">Ir para o conteúdo</a>
${renderHeader({prefix,active:'news',article})}
<main id="conteudo" tabindex="-1">${body}</main>
${renderFooter({prefix,variant:'editorial'})}
</body></html>\n`;
}
function breadcrumb(prefix, title) {
  const items = [{ label: 'Início', href: 'index.html' }, { label: 'Notícias', href: 'noticias.html' }];
  if (title) items.push({ label: title });
  return require('../src/components/breadcrumb')({ items, label: 'Você está aqui' }, prefix);
}
function pagination(data, prefix) {
  if (data.pages <= 1) return '';
  const pages = new Set([1, data.pages, data.current-1, data.current, data.current+1]);
  const numbers = [...pages].filter(n => n > 0 && n <= data.pages).sort((a,b) => a-b);
  let last = 0;
  const links = numbers.map(n => {
    const gap = last && n-last > 1 ? '<span class="pagination-gap" aria-hidden="true">…</span>' : '';
    last = n;
    return gap + (n === data.current ? `<span class="pagination-current" aria-current="page" aria-label="Página ${n}, atual">${n}</span>` : `<a href="${prefix+archiveURL(n)}#todas-as-noticias" aria-label="Página ${n}">${n}</a>`);
  }).join('');
  return `<nav class="editorial-pagination" aria-label="Paginação de notícias">
    ${data.current>1?`<a class="pagination-direction" rel="prev" href="${prefix+archiveURL(data.current-1)}#todas-as-noticias">← <span>Anterior</span></a>`:'<span class="pagination-direction" aria-disabled="true">← <span>Anterior</span></span>'}
    <div class="pagination-numbers">${links}</div>
    ${data.current<data.pages?`<a class="pagination-direction" rel="next" href="${prefix+archiveURL(data.current+1)}#todas-as-noticias"><span>Próxima</span> →</a>`:'<span class="pagination-direction" aria-disabled="true"><span>Próxima</span> →</span>'}</nav>`;
}
const first = E.archive(all);
const topics = [
  ['educacao','Educação'], ['ciencia','Ciência e tecnologia'],
  ['formacao-profissional','Formação profissional'], ['cooperacao','Cooperação']
].filter(([key]) => all.filter(item => item.topics?.includes(key)).length > 1);
function explorer() {
  return `<div class="archive-explorer" hidden>
    <form class="archive-search" role="search" aria-label="Buscar no acervo de notícias">
      <label for="news-search">Encontre uma história</label>
      <div class="archive-search-field"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="news-search" name="q" type="search" placeholder="Buscar notícias" maxlength="120" autocomplete="off"><button type="button" class="archive-search-clear" aria-label="Limpar busca" hidden>×</button><button class="archive-search-submit" type="submit">Buscar</button></div>
    </form>
    <div class="archive-topics"><span id="news-topics-label">Explore por assunto</span><div class="archive-chips" role="group" aria-labelledby="news-topics-label"><button type="button" data-topic="" aria-pressed="true">Todas</button>${topics.map(([key,label])=>`<button type="button" data-topic="${key}" aria-pressed="false">${label}</button>`).join('')}</div></div>
  </div>`;
}
function initiativeLink(prefix) {
  return `<aside class="editorial-invitation"><div><p class="editorial-label">Conheça de perto</p><h2>Histórias que continuam em nossas iniciativas.</h2><p>Explore os programas e projetos que conectam a FAG à comunidade.</p></div><a class="news-archive-link" href="${prefix}programas-e-projetos.html">Conhecer as iniciativas ${E.arrow}</a></aside>`;
}
for (let n=1; n<=first.pages; n++) {
  const data = E.archive(all,n), prefix = n===1?'':'../';
  const feature = data.featured ? `<section class="archive-feature" aria-label="Notícia em destaque"><div class="archive-feature-heading"><span>Em foco</span><span>Educação, ciência e comunidade</span></div>${E.card(data.featured,{prefix,featured:true,heading:'h2',namespace:'feature',sizes:'(max-width: 767px) calc(100vw - 40px), (max-width: 1380px) 56vw, 744px',eager:true})}</section>`:'';
  const title = n===1?'Notícias':`Notícias — página ${n}`;
  const body = `<div class="editorial-shell">
    <header class="editorial-opening">${breadcrumb(prefix)}<div class="editorial-opening-grid"><div><p class="news-eyebrow"><span class="news-marker" aria-hidden="true"></span>FAG · Notícias</p><h1>Notícias<span class="editorial-title-dot" aria-hidden="true">.</span></h1></div>
    <p class="editorial-intro">Acompanhe as notícias, projetos e iniciativas da FAG. Histórias que conectam <strong>educação, ciência e comunidade.</strong></p></div><div class="editorial-orbit" aria-hidden="true"></div></header>
    ${feature}<section class="archive-list" aria-labelledby="todas-as-noticias" data-archive-prefix="${prefix}"><header class="archive-list-head"><div><p class="editorial-label">O que acontece na FAG</p><h2 id="todas-as-noticias" tabindex="-1">Todas as notícias</h2></div><p class="archive-count">${data.total} ${data.total===1?'publicação':'publicações'} <span aria-hidden="true">/</span> Página ${n} de ${data.pages}</p></header>
    ${explorer()}<p class="archive-feedback" role="status" aria-live="polite" aria-atomic="true" hidden></p>
    ${data.items.length?`<div class="editorial-grid">${data.items.map(i => E.card(i,{prefix,namespace:'archive'})).join('')}</div>`:`<p class="editorial-state">${data.featured?'A publicação disponível está apresentada no destaque acima.':'Novas notícias serão publicadas em breve. Acompanhe as próximas atualizações da FAG.'}</p>`}
    <div class="archive-empty" hidden><span class="archive-empty-mark" aria-hidden="true">↗</span><h3>Nenhuma notícia encontrada</h3><p>Tente utilizar outro termo ou alterar os filtros selecionados.</p><button type="button" class="news-archive-link" data-reset-news>Limpar filtros</button></div>
    <div class="archive-more" hidden><button type="button" class="news-archive-link">Carregar mais notícias ${E.arrow}</button></div>
    ${pagination(data,prefix)}</section>${initiativeLink(prefix)}</div>`;
  const extraHead = `${n>1?`<link rel="prev" href="${site+'/'+archiveURL(n-1)}">`:''}${n<data.pages?`<link rel="next" href="${site+'/'+archiveURL(n+1)}">`:''}`;
  outputs.set(archiveURL(n),page({title,description:'Acompanhe notícias, acontecimentos, projetos e iniciativas da FAG em Tanguá.',route:archiveURL(n),prefix,body,extraHead,archive:true}));
}
function blocksHTML(item,prefix) {
  return item.blocks.map(block => {
    if (!['p','h2','h3','li','blockquote'].includes(block.type) || !Array.isArray(block.runs)) throw new Error(`Invalid content block in ${item.id}`);
    const text = block.runs.map(run => {
      const content = esc(run.text).replace(/\n/g,'<br>');
      const href = run.href && contentLink(run.href,prefix);
      return href?`<a href="${esc(href)}">${content}</a>`:content;
    }).join('');
    return block.type==='li'?`<ul><li>${text}</li></ul>`:`<${block.type}>${text}</${block.type}>`;
  }).join('\n');
}
for (const item of all) {
  const prefix = '../', peers = E.related(item,all);
  const words = item.blocks.flatMap(block => block.runs.map(run => run.text)).join(' ').trim().split(/\s+/).length;
  const readingMinutes = Math.max(1,Math.ceil(words/200));
  const shareURL = site+'/'+E.url(item);
  const gallery = item.gallery?.length ? `<section class="story-gallery" aria-labelledby="galeria"><h2 id="galeria">Registros do acontecimento</h2><div>${item.gallery.map(image => E.imageHTML(item,{prefix,image,sizes:'(max-width: 767px) calc(100vw - 40px), 590px'})).join('')}</div></section>`:'';
  const body = `<div class="story-progress" aria-hidden="true" hidden><span></span></div><article class="editorial-shell story"><header class="story-opening">${breadcrumb(prefix,item.title)}<div class="story-heading"><p class="news-eyebrow"><span class="news-marker" aria-hidden="true"></span>FAG · Notícias</p><h1>${esc(item.title)}</h1><p class="story-deck">${esc(item.subtitle || item.excerpt)}</p><div class="story-byline">${E.meta(item)}<span class="story-reading-time">${readingMinutes} min de leitura estimada</span></div></div></header>
    <div class="story-cover">${E.imageHTML(item,{prefix,eager:true,sizes:'(max-width: 1240px) calc(100vw - 40px), 1120px'})}</div>
    <div class="story-body">${item.subtitle?`<p class="story-subtitle">${esc(item.subtitle)}</p>`:''}${blocksHTML(item,prefix)}</div>${gallery}
    <section class="story-share" aria-label="Compartilhar notícia"><div><p class="editorial-label">Leve esta história adiante</p><h2>Compartilhe a notícia</h2></div><div class="story-share-actions"><a href="https://wa.me/?text=${encodeURIComponent(item.title+' '+shareURL)}" target="_blank" rel="noopener noreferrer" aria-label="Compartilhar no WhatsApp (abre em nova aba)">WhatsApp ${E.arrow}</a><button type="button" data-copy-link="${esc(shareURL)}" hidden>Copiar link <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M15 8V4H4v11h4"/></svg></button></div><p class="story-copy-status" role="status" aria-live="polite" aria-atomic="true"></p></section>
    <div class="story-return"><a class="news-archive-link" href="../noticias.html"><span aria-hidden="true">←</span> Voltar para Notícias</a></div></article>
    ${peers.length?`<section class="story-related" aria-labelledby="relacionadas"><div class="editorial-shell"><header class="archive-list-head"><div><p class="editorial-label">Continue a leitura</p><h2 id="relacionadas">Notícias relacionadas</h2></div><p>Outras histórias sobre o mesmo assunto.</p></header><div class="editorial-grid">${peers.map(i => E.card(i,{prefix,namespace:'related'})).join('')}</div></div></section>`:''}`;
  const structured = JSON.stringify({'@context':'https://schema.org','@type':'NewsArticle',headline:item.title,datePublished:item.publishedAt,
    mainEntityOfPage:site+'/'+E.url(item), publisher:{'@type':'Organization',name:'FAG'}}).replace(/</g,'\\u003c');
  outputs.set(E.url(item),page({title:item.title,description:item.excerpt,route:E.url(item),prefix,body,article:true,image:item.image?.src,extraHead:`<script type="application/ld+json">${structured}</script>`}));
}
outputs.set('404.html',page({title:'Página não encontrada',description:'Retorne ao arquivo de notícias da FAG.',route:'404.html',prefix:'/',noindex:true,
  body:'<div class="editorial-shell editorial-error"><p class="news-eyebrow">FAG · 404</p><h1>Página não encontrada</h1><p>Este endereço não está disponível. Encontre as publicações no arquivo de Notícias.</p><a class="news-archive-link" href="/noticias.html">Voltar para Notícias</a></div>'}));
const metadata = E.selectNews(all).map(({blocks,gallery,sourceUrl,sourceId,...item}) => ({...item,url:E.url(item)}));
outputs.set('assets/js/data/news.js','/* Generated from content/news.json. Run node scripts/build-news.js. */\nwindow.FAG_NEWS_DATA = '+JSON.stringify({items:metadata},null,2)+';\n');
const archiveMetadata = all.map(({blocks,gallery,sourceUrl,sourceId,...item}) => item);
outputs.set('assets/js/data/news-archive.js','/* Generated from content/news.json. Archive search index. */\nwindow.FAG_NEWS_ARCHIVE = '+JSON.stringify({items:archiveMetadata,topics},null,2)+';\n');
const manifestPath = path.join(root,'content/news-generated.json');
const previous = fs.existsSync(manifestPath) ? JSON.parse(fs.readFileSync(manifestPath,'utf8')) : [];
const obsolete = previous.filter(relative => /^noticias\/[a-z0-9-]+\.html$/.test(relative) && !outputs.has(relative));
outputs.set('content/news-generated.json',JSON.stringify([...outputs.keys()],null,2)+'\n');
module.exports = { outputs, obsolete };
// Keep the original entry point compatible; the complete build also updates the home feed.
if (require.main === module) require('./build-site').build();
