'use strict';
const site = require('../config/site');
const pages = require('../config/pages');
const { template } = require('./lib/templates');
const { writeOutputs } = require('./lib/outputs');
const head = require('../src/components/head');
const header = require('../src/components/header');
const footer = require('../src/components/footer');
const C = require('../src/components/courses');
const E = require('../assets/js/shared/news-model');
const news = require('../content/news.json');

function build() {
  const editorial = require('./build-news');
  const outputs = new Map(editorial.outputs);
  const selected = E.selectNews(news.items);
  const asymmetric = selected.length === 4 && selected[0].featured === true;
  const newsFeed = `<div class="news-grid${asymmetric ? ' has-featured' : ''}" data-news-grid data-rendered="true" data-count="${selected.length}">${selected.map((item, index) => E.card(item, {
    featured: index === 0 && item.featured === true, namespace: 'home',
    sizes: asymmetric ? index === 0 ? '(max-width: 1024px) calc(100vw - 48px), 714px' : '(max-width: 767px) calc(100vw - 40px), (max-width: 1024px) 46vw, 150px' : undefined
  })).join('')}</div>`;
  for (const page of pages) {
    const prefix = '../'.repeat(page.route.split('/').length - 1);
    const markup = template('pages/' + page.template, {
      head: head({ ...page, prefix, styles: page.styles.map(name => `assets/css/${name}.css`), scripts: page.scripts.map(name => `assets/js/${name}.js`) }),
      header: header({ prefix, active: page.active, variant: page.header }),
      footer: page.footer ? footer({ prefix, variant: page.footer, home: page.active === 'home' }) : '',
      scripts: '', newsFeed,
      courseCards: C.courses.map((course, index) => C.card(course, index, prefix)).join('\n'),
      courseDetails: C.courses.map((course, index) => C.detail(course, index, prefix)).join('\n'),
      courseIndex: C.courses.map(C.index).join('\n'),
      prefix
    }).replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by scripts/build-site.js. Edit src/pages and src/components. -->');
    if (outputs.has(page.route)) throw new Error('Duplicate page route: ' + page.route);
    outputs.set(page.route, markup);
  }
  const routes = [...outputs.keys()].filter(route => route.endsWith('.html') && route !== '404.html');
  outputs.set('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${routes.map(route => `  <url><loc>${E.escape(site.url + '/' + (route === 'index.html' ? '' : route))}</loc></url>`).join('\n')}\n</urlset>\n`);
  outputs.set('robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${site.url}/sitemap.xml\n`);
  writeOutputs(outputs, { check: process.argv.includes('--check'), obsolete: editorial.obsolete });
}
module.exports = { build };
if (require.main === module) build();
