/* Build static editorial pages and the small home feed from one source of truth.
   Run: node scripts/build-news.js [--check]. No packages or network required. */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const E = require('../assets/news-shared.js');
const root = path.resolve(__dirname, '..');
const source = JSON.parse(fs.readFileSync(path.join(root, 'content/news.json'), 'utf8'));
const site = (process.env.FAG_SITE_URL || 'https://fag.tangua.rj.gov.br').replace(/\/$/, '');
const all = E.published(source.items);
const esc = E.escape;
const outputs = new Map();
const ids = new Set(), slugs = new Set();
for (const item of source.items) {
  if (!E.slug(item.slug) || !E.slug(item.id) || ids.has(item.id) || slugs.has(item.slug)) throw new Error(`Invalid/duplicate identity: ${item.id}`);
  if (!E.date(item.publishedAt) || !item.title || !item.category || !Array.isArray(item.blocks)) throw new Error(`Incomplete article: ${item.id}`);
  ids.add(item.id); slugs.add(item.slug);
}
const archiveURL = page => page === 1 ? 'noticias.html' : `noticias/pagina-${page}.html`;
const internal = new Map(all.map(i => [i.sourceUrl, E.url(i)]));
function contentLink(href, prefix) {
  if (internal.has(href)) return prefix + internal.get(href);
  if (/^https:\/\/fag\.tangua\.rj\.gov\.br\/category\/noticias\//.test(href)) return prefix+'noticias.html';
  if (/^https?:\/\//.test(href)) return E.safeURL(href);
  return E.safeURL(href) ? prefix+href : '';
}
function page({title, description, route, prefix='', body, article=false, noindex=false, extraHead=''}) {
  const links = `<a href="${prefix}index.html">Início</a><a href="${prefix}index.html#sobre-a-fag">A Fundação</a><a href="${prefix}cursos.html">Cursos e oportunidades</a><a href="${prefix}index.html#programas-e-projetos">Programas e projetos</a><a href="${prefix}noticias.html" class="is-active" aria-current="${article?'true':'page'}">Notícias</a>`;
  return `<!DOCTYPE html>
<!-- Generated by scripts/build-news.js. Edit content/news.json or the shared templates. -->
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#F5F8F1"><title>${esc(title)} — FAG</title><meta name="description" content="${esc(description)}">
${noindex?'<meta name="robots" content="noindex">':`<link rel="canonical" href="${esc(site+'/'+route)}">`}
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="${prefix}assets/catalog.css"><link rel="stylesheet" href="${prefix}assets/news.css"><link rel="stylesheet" href="${prefix}assets/news-pages.css">${extraHead}
<script src="${prefix}assets/news-interactions.js" defer></script></head>
<body class="editorial-page${article?' editorial-page--article':''}"><a class="skip-link" href="#conteudo">Ir para o conteúdo</a>
<header class="editorial-header"><div class="editorial-header-shell">
<a class="editorial-brand" href="${prefix}index.html" aria-label="FAG — início"><img src="${prefix}assets/raw_files/Logo.png" width="1828" height="860" alt="FAG"></a>
<nav class="editorial-desktop-nav" aria-label="Navegação principal">${links}</nav>
<details class="editorial-menu"><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Navegação principal móvel">${links}</nav></details>
</div></header>
<main id="conteudo" tabindex="-1">${body}</main>
<footer class="editorial-footer"><div class="editorial-shell"><a href="${prefix}index.html" class="editorial-footer-brand" aria-label="FAG — início"><img src="${prefix}assets/raw_files/Logo.png" width="1828" height="860" alt="FAG"></a><p>Precisão técnica.<br><span>Presença humana.</span></p><nav aria-label="Navegação do rodapé"><a href="${prefix}noticias.html">Notícias</a><a href="${prefix}index.html">Voltar ao início ${E.arrow}</a></nav></div></footer>
</body></html>\n`;
}
function breadcrumb(prefix, title) {
  return `<nav class="editorial-breadcrumb" aria-label="Você está aqui"><ol><li><a href="${prefix}index.html">Início</a></li><li>${title?`<a href="${prefix}noticias.html">Notícias</a>`:'<span aria-current="page">Notícias</span>'}</li>${title?`<li><span aria-current="page">${esc(title)}</span></li>`:''}</ol></nav>`;
}
function pagination(data, prefix) {
  if (data.pages <= 1) return '';
  const pages = new Set([1, data.pages, data.current-1, data.current, data.current+1]);
  const numbers = [...pages].filter(n => n > 0 && n <= data.pages).sort((a,b) => a-b);
  let last = 0;
  const links = numbers.map(n => {
    const gap = last && n-last > 1 ? '<span class="pagination-gap" aria-hidden="true">…</span>' : '';
    last = n;
    return gap + (n === data.current ? `<span class="pagination-current" aria-current="page" aria-label="Página ${n}, atual">${n}</span>` : `<a href="${prefix+archiveURL(n)}#todas-as-noticias" aria-label="Página ${n}">${n}</a>`);
  }).join('');
  return `<nav class="editorial-pagination" aria-label="Paginação de notícias">
    ${data.current>1?`<a class="pagination-direction" rel="prev" href="${prefix+archiveURL(data.current-1)}#todas-as-noticias">← <span>Anterior</span></a>`:'<span class="pagination-direction" aria-disabled="true">← <span>Anterior</span></span>'}
    <div class="pagination-numbers">${links}</div>
    ${data.current<data.pages?`<a class="pagination-direction" rel="next" href="${prefix+archiveURL(data.current+1)}#todas-as-noticias"><span>Próxima</span> →</a>`:'<span class="pagination-direction" aria-disabled="true"><span>Próxima</span> →</span>'}</nav>`;
}
const first = E.archive(all);
for (let n=1; n<=first.pages; n++) {
  const data = E.archive(all,n), prefix = n===1?'':'../';
  const feature = data.featured ? `<section class="archive-feature" aria-label="Notícia em destaque">${E.card(data.featured,{prefix,featured:true,heading:'h2',namespace:'feature',sizes:'(max-width: 1024px) calc(100vw - 48px), 714px',eager:true})}</section>`:'';
  const title = n===1?'Notícias':`Notícias — página ${n}`;
  const body = `<div class="editorial-shell">
    <header class="editorial-opening">${breadcrumb(prefix)}<div class="editorial-opening-grid"><div><p class="news-eyebrow"><span class="news-marker" aria-hidden="true"></span>Atualizações · FAG</p><h1>Notícias<span class="editorial-title-dot" aria-hidden="true">.</span></h1></div>
    <p class="editorial-intro">Acontecimentos, projetos e iniciativas que aproximam educação, ciência e comunidade. Acompanhe a FAG e as histórias que fazem parte da nossa trajetória.</p></div></header>
    ${feature}<section class="archive-list" aria-labelledby="todas-as-noticias"><header class="archive-list-head"><div><p class="editorial-label">Arquivo editorial</p><h2 id="todas-as-noticias" tabindex="-1">Todas as notícias</h2></div><p>${data.total} ${data.total===1?'publicação':'publicações'} <span aria-hidden="true">/</span> Página ${n} de ${data.pages}</p></header>
    ${data.items.length?`<div class="editorial-grid">${data.items.map(i => E.card(i,{prefix,namespace:'archive'})).join('')}</div>`:`<p class="editorial-state">${data.featured?'A publicação disponível está apresentada no destaque acima.':'Novas notícias serão publicadas em breve. Acompanhe as próximas atualizações da FAG.'}</p>`}
    ${pagination(data,prefix)}</section></div>`;
  const extraHead = `${n>1?`<link rel="prev" href="${site+'/'+archiveURL(n-1)}">`:''}${n<data.pages?`<link rel="next" href="${site+'/'+archiveURL(n+1)}">`:''}`;
  outputs.set(archiveURL(n),page({title,description:'Acompanhe notícias, acontecimentos, projetos e iniciativas da FAG em Tanguá.',route:archiveURL(n),prefix,body,extraHead}));
}
function blocksHTML(item,prefix) {
  return item.blocks.map(block => {
    if (!['p','h2','h3','li','blockquote'].includes(block.type) || !Array.isArray(block.runs)) throw new Error(`Invalid content block in ${item.id}`);
    const text = block.runs.map(run => {
      const content = esc(run.text).replace(/\n/g,'<br>');
      const href = run.href && contentLink(run.href,prefix);
      return href?`<a href="${esc(href)}">${content}</a>`:content;
    }).join('');
    return block.type==='li'?`<ul><li>${text}</li></ul>`:`<${block.type}>${text}</${block.type}>`;
  }).join('\n');
}
for (const item of all) {
  const prefix = '../', peers = E.related(item,all);
  const gallery = item.gallery?.length ? `<section class="story-gallery" aria-labelledby="galeria"><h2 id="galeria">Registros do acontecimento</h2><div>${item.gallery.map(image => E.imageHTML(item,{prefix,image,sizes:'(max-width: 767px) calc(100vw - 40px), 590px'})).join('')}</div></section>`:'';
  const body = `<article class="editorial-shell story"><header class="story-opening">${breadcrumb(prefix,item.title)}<div class="story-heading">${E.meta(item)}<h1>${esc(item.title)}</h1></div></header>
    <div class="story-cover">${E.imageHTML(item,{prefix,eager:true,sizes:'(max-width: 1240px) calc(100vw - 40px), 1120px'})}</div>
    <div class="story-body">${item.subtitle?`<p class="story-subtitle">${esc(item.subtitle)}</p>`:''}${blocksHTML(item,prefix)}</div>${gallery}
    <div class="story-return"><a class="news-archive-link" href="../noticias.html"><span aria-hidden="true">←</span> Voltar para Notícias</a></div></article>
    ${peers.length?`<section class="story-related" aria-labelledby="relacionadas"><div class="editorial-shell"><header class="archive-list-head"><div><p class="editorial-label">Continue a leitura</p><h2 id="relacionadas">Notícias relacionadas</h2></div><p>Outras histórias sobre o mesmo assunto.</p></header><div class="editorial-grid">${peers.map(i => E.card(i,{prefix,namespace:'related'})).join('')}</div></div></section>`:''}`;
  const structured = JSON.stringify({'@context':'https://schema.org','@type':'NewsArticle',headline:item.title,datePublished:item.publishedAt,
    mainEntityOfPage:site+'/'+E.url(item), publisher:{'@type':'Organization',name:'FAG'}}).replace(/</g,'\\u003c');
  outputs.set(E.url(item),page({title:item.title,description:item.excerpt,route:E.url(item),prefix,body,article:true,extraHead:`<script type="application/ld+json">${structured}</script>`}));
}
outputs.set('404.html',page({title:'Página não encontrada',description:'Retorne ao arquivo de notícias da FAG.',route:'404.html',prefix:'/',noindex:true,
  body:'<div class="editorial-shell editorial-error"><p class="news-eyebrow">FAG · 404</p><h1>Página não encontrada</h1><p>Este endereço não está disponível. Encontre as publicações no arquivo de Notícias.</p><a class="news-archive-link" href="/noticias.html">Voltar para Notícias</a></div>'}));
const metadata = E.selectNews(all).map(({blocks,gallery,sourceUrl,sourceId,...item}) => ({...item,url:E.url(item)}));
outputs.set('assets/news-data.js','/* Generated from content/news.json. Run node scripts/build-news.js. */\nwindow.FAG_NEWS_DATA = '+JSON.stringify({items:metadata},null,2)+';\n');
const check = process.argv.includes('--check');
const manifestPath = path.join(root,'content/news-generated.json');
const previous = fs.existsSync(manifestPath) ? JSON.parse(fs.readFileSync(manifestPath,'utf8')) : [];
const obsolete = previous.filter(relative => !outputs.has(relative));
// Only remove formerly generated article/archive files, never arbitrary files.
for (const relative of obsolete) {
  const target = path.resolve(root,relative);
  if (!/^noticias\/[a-z0-9-]+\.html$/.test(relative) || !target.startsWith(root+path.sep)) throw new Error('Unsafe generated path');
  if (fs.existsSync(target) && !fs.readFileSync(target,'utf8').includes('Generated by scripts/build-news.js.')) throw new Error('Modified output requires review: '+relative);
}
outputs.set('content/news-generated.json',JSON.stringify([...outputs.keys()],null,2)+'\n');
let changed = 0;
for (const [relative,content] of outputs) {
  const target = path.join(root,relative);
  if (fs.existsSync(target) && fs.readFileSync(target,'utf8')===content) continue;
  changed++;
  if (!check) { fs.mkdirSync(path.dirname(target),{recursive:true}); fs.writeFileSync(target,content); }
}
if (!check) obsolete.forEach(relative => { const target=path.join(root,relative); if(fs.existsSync(target)) fs.unlinkSync(target); });
if (check && (changed || obsolete.length)) { console.error(`${changed} editorial outputs need rebuilding; ${obsolete.length} obsolete pages.`); process.exitCode=1; }
else console.log(`${all.length} articles; ${first.pages} archive pages; ${check?'all outputs up to date':changed+' files generated'}.`);
